feat: Add fixes for block-lang rule
sveltejs/eslint-plugin-svelte pull request #844
Opened 2024-08-26 11:18 UTC by Winter

I wanted eslint to automatically fix script/style errors from the block-lang rule.

The `lang` fixes will only apply when a script/style config value contains only a single, non-null value.

```html

 
<script>
</script>
```

```html

 
<script lang="ts">
</script>
```

```html

<script>
</script>
 
<script lang="ts">
</script>
```

```html

<script context="module">
</script>
 
<script lang="ts" context="module">
</script>
```

```html

<script module>
</script>
 
<script lang="ts" module>
</script>
```
*The same logic applies to the `style` tag except will create at the bottom of the file*

2024-09-13 02:55 UTC, ota-meshi requested changes
Thank you for this PR!

I think changing the `lang` attribute may break the component.
Auto-fix needs to be safe, so could you change it to use the suggestions API instead?
If multiple langs ​​are allowed, we could show multiple suggestions.

2024-12-30 05:58 UTC, baseballyama commented on packages/eslint-plugin-svelte/tests/fixtures/rules/block-lang/invalid/script/javascript/javascript-as-style-lang01-errors.yaml
> +        <style lang="javascript"></style>
This is wrong. I will fix this but I need to go outside now.

2024-12-30 07:38 UTC, baseballyama commented on packages/eslint-plugin-svelte/tests/fixtures/rules/block-lang/invalid/script/javascript/javascript-as-style-lang01-errors.yaml
> +        <style lang="javascript"></style>
Upon carefully reviewing the test cases, this is correct.😇

2024-12-30 08:18 UTC, baseballyama approved these changes

2024-12-30 08:29 UTC, merged