feat: added the `consistent-selector-style` rule
sveltejs/eslint-plugin-svelte pull request #925
Opened 2024-11-22 15:37 UTC by marekdedic

Closes #898

2024-12-14 23:10 UTC, marekdedic commented
Hi, @ota-meshi! This one is I think ready for review, however, it needs sveltejs/svelte-eslint-parser#619 and #965 first.

2025-01-03 14:33 UTC, marekdedic commented on packages/eslint-plugin-svelte/src/rules/consistent-selector-style.ts
> +	if (types.size > 1) {
This doesn't report any selection which could be replaced by multiple type selections (e.g. replacing `.emphasized {}` by `i, b {}`). That can be added later I think (maybe gated with a configuration option?)

2025-01-14 04:07 UTC, ota-meshi requested changes
Thank you for this PR!
I have a few comments.

2025-01-14 04:07 UTC, ota-meshi commented on packages/eslint-plugin-svelte/src/rules/consistent-selector-style.ts
> +	return (
Couldn't you compare it like this?

```js
return (
  array1.length === array2.length && 
  array1.every(e => array2.includes(e))
)
```

2025-01-14 07:52 UTC, marekdedic commented on packages/eslint-plugin-svelte/src/rules/consistent-selector-style.ts
> +	return (
You could, but it's slower (n² instead of n log n)

2025-01-14 09:17 UTC, marekdedic commented on packages/eslint-plugin-svelte/src/rules/consistent-selector-style.ts
> +function checkSelectorsInPostCSSNode(node: AnyNode, ruleGlobals: RuleGlobals): void {
You could, but `ruleGlobals` need to be passed down so many functions... Putting them all in `create` would make it really long and unreadable, so I don't think that's a good idea, what do you think?

2025-01-14 09:22 UTC, marekdedic commented on docs/rules/consistent-selector-style.md
> +- `style` ... A list of style preferences. Default `["type", "id", "class"]`.
I added a better description further up the file in the rule details.

2025-01-14 10:13 UTC, ota-meshi commented on packages/eslint-plugin-svelte/src/rules/consistent-selector-style.ts
> +function checkSelectorsInPostCSSNode(node: AnyNode, ruleGlobals: RuleGlobals): void {
I think I understand your point.

However, in my opinion, I would rather have a longer `create()` function, which would make it harder to read, than having to pass many properties to the current `ruleGlobals` and make them harder to keep track of.
I think that RuleGlobals can't be understood without reading the `create()` function after all.

But, I may not always be of this opinion. I may have a different opinion for a different rule implementation, but that's how I feel about this PR.

2025-01-14 10:13 UTC, ota-meshi commented on packages/eslint-plugin-svelte/src/rules/consistent-selector-style.ts
> +	return (
In my opinion, I don't expect any performance issues with non-malicious `.svelte` files (please let me know if this isn't the case).
For now I prefer to keep the function size at 2 lines.

2025-01-15 00:24 UTC, ota-meshi approved these changes
LGTM! Thank you!

2025-01-15 00:24 UTC, merged